# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
name: Build and Deploy

on:
  push:
    branches:
      - irkode
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x

      - name: Build
        run: |
          npm ci
          npm run build --if-present

      - name: Deploy
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto deploy build results
          commit_options: '--signoff'
          file_pattern: dist/*
          commit_user_name: Auto commit
          skip_fetch: true
          skip_checkout: true
          name: dist
          path: dist/
